#!/usr/bin/env bash
# Keep the roost formula in navbytes/homebrew-tap tracking the release the
# workflow just built: render Formula/roost.rb from the release's checksums
# and push it to the tap. Idempotent — re-running for an already-synced
# version pushes nothing. Mirrors vee's scripts/update-homebrew-cask.sh, the
# same pattern against the same tap.
#
# Runs from the Release workflow's `release` job, which has the combined
# checksum file at dist/SHA256SUMS.txt. Expects, in the environment:
#   HOMEBREW_TAP_TOKEN  fine-grained PAT with contents:write on
#                       navbytes/homebrew-tap (unused with RENDER_ONLY=1)
#   RELEASE_TAG         the release tag, e.g. v0.1.5
#   SUMS_FILE           path to SHA256SUMS.txt (default: dist/SHA256SUMS.txt)
#   RENDER_ONLY         set to 1 to print the rendered formula to stdout and
#                       exit — the dry-run / manual-fallback path
#
# The workflow step is skipped when HOMEBREW_TAP_TOKEN is absent, so forks
# and unconfigured repos still release cleanly (the tap just isn't updated).
set -euo pipefail

: "${RELEASE_TAG:?RELEASE_TAG is required (e.g. v0.1.5)}"
SUMS_FILE="${SUMS_FILE:-dist/SHA256SUMS.txt}"

if [ ! -f "$SUMS_FILE" ]; then
  echo "::error::$SUMS_FILE not found; run this after the checksums are combined." >&2
  exit 1
fi

version="${RELEASE_TAG#v}"

sum_for() {
  local target="$1" sum
  sum="$(grep -- "roost-${version}-${target}.tar.gz" "$SUMS_FILE" | awk '{print $1}')"
  if ! [[ "$sum" =~ ^[0-9a-f]{64}$ ]]; then
    echo "::error::no valid sha256 for ${target} in $SUMS_FILE" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

sha_mac_arm="$(sum_for aarch64-apple-darwin)"
sha_mac_x64="$(sum_for x86_64-apple-darwin)"
sha_linux_arm="$(sum_for aarch64-unknown-linux-gnu)"
sha_linux_x64="$(sum_for x86_64-unknown-linux-gnu)"

render() {
  cat <<EOF
# Generated by navbytes/roost's release workflow — see
# scripts/update-homebrew-formula.sh there, which renders this file from the
# release's SHA256SUMS.txt. Edit that script, not this file.
class Roost < Formula
  desc "Session-native terminal multiplexer for AI agent CLIs"
  homepage "https://github.com/navbytes/roost"
  version "${version}"
  license "MIT"

  # \`url\`/\`sha256\` aren't permitted inside on_macos/on_linux blocks (brew
  # style: FormulaAudit/ComponentsOrder) — plain OS/CPU conditionals instead.
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-aarch64-apple-darwin.tar.gz"
    sha256 "${sha_mac_arm}"
  elsif OS.mac?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-x86_64-apple-darwin.tar.gz"
    sha256 "${sha_mac_x64}"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-aarch64-unknown-linux-gnu.tar.gz"
    sha256 "${sha_linux_arm}"
  elsif OS.linux?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "${sha_linux_x64}"
  end

  def install
    bin.install "roost"
  end

  test do
    assert_match "roost spawn ADAPTER", shell_output("#{bin}/roost --help 2>&1")
  end
end
EOF
}

if [ "${RENDER_ONLY:-}" = "1" ]; then
  render
  exit 0
fi

: "${HOMEBREW_TAP_TOKEN:?HOMEBREW_TAP_TOKEN is required}"
echo "Formula target: roost ${version}"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT
git clone --depth 1 \
  "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/navbytes/homebrew-tap.git" \
  "$workdir/tap"

tap="$workdir/tap"
mkdir -p "$tap/Formula"
render > "$tap/Formula/roost.rb"

cd "$tap"
git add -A
if git diff --cached --quiet; then
  echo "Tap already up to date for ${version}; nothing to push."
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git commit -m "roost ${version}"
git push
echo "Pushed tap update for roost ${version}."
