//! Keep agent-CLI status integrations in sync with this build.
//!
//! roost's status/session reporting depends on each agent CLI being wired to
//! roost's socket. Because roost doesn't ship a package for either, users
//! would otherwise wire it up by hand — and it then silently rots when
//! roost's socket protocol changes (e.g. the per-pane token, which roost now
//! *requires*: a stale integration's messages are dropped).
//!
//! On startup we install/update both automatically, but only when the tool
//! is actually set up (we never create `~/.pi` or `~/.claude` ourselves), and
//! only when the on-disk copy is missing or differs. Opt out with
//! `ROOST_NO_EXT_INSTALL`.
//!
//! - pi: a single file we own outright (`~/.pi/agent/extensions/roost.ts`) —
//!   compare-and-overwrite, see `ensure_pi_extension`.
//! - Claude Code: three hook entries inside `~/.claude/settings.json`, a file
//!   the *user* owns and may already have their own content in — merge, not
//!   overwrite, see `ensure_claude_hooks`.

use std::path::{Path, PathBuf};

/// The extension source, embedded at build time so the binary is self-contained.
const BUNDLED: &str = include_str!("../../extensions/roost.ts");

/// Ensure `~/.pi/agent/extensions/roost.ts` matches this build. Returns a short
/// message to surface when it installed or updated the file, else None.
pub fn ensure_pi_extension() -> Option<String> {
    if std::env::var_os("ROOST_NO_EXT_INSTALL").is_some() {
        return None;
    }
    let agent_dir = dirs::home_dir()?.join(".pi").join("agent");
    // Only touch things when pi is present — never create ~/.pi ourselves.
    if !agent_dir.is_dir() {
        return None;
    }
    let ext_dir = agent_dir.join("extensions");
    let target = ext_dir.join("roost.ts");

    let existing = std::fs::read_to_string(&target).ok();
    if existing.as_deref() == Some(BUNDLED) {
        return None; // already current
    }
    let updating = existing.is_some();

    std::fs::create_dir_all(&ext_dir).ok()?;
    write_atomic(&target, BUNDLED)?;

    Some(if updating {
        "updated the roost pi extension to match this build".into()
    } else {
        "installed the roost pi extension (~/.pi/agent/extensions/roost.ts)".into()
    })
}

/// Ensure `~/.claude/settings.json` has roost's three status hooks (see
/// `extensions/claude-code-hooks.md`), merged into whatever's already there.
/// Returns a short message when it installed, updated, or refused to touch
/// the file; None when nothing changed. Mirrors `ensure_pi_extension`'s
/// contract (same opt-out, same "only when the tool is set up" rule, same
/// "message only on an actual change" shape) — the difference is `settings.
/// json` is user-owned, so this merges instead of overwriting; see
/// `merge_claude_hooks`.
pub fn ensure_claude_hooks() -> Option<String> {
    if std::env::var_os("ROOST_NO_EXT_INSTALL").is_some() {
        return None;
    }
    let claude_dir = dirs::home_dir()?.join(".claude");
    // Only touch things when Claude Code is present — never create ~/.claude.
    if !claude_dir.is_dir() {
        return None;
    }
    let exe = std::env::current_exe().ok()?;
    merge_claude_hooks(&claude_dir.join("settings.json"), &exe.to_string_lossy())
}

/// The Claude Code hook events roost wires up, and the status each reports.
/// PreToolUse fires at the start of a turn (working), Stop at the end
/// (waiting), Notification on Claude Code's own permission/idle prompts
/// (needs_input) — see `extensions/claude-code-hooks.md`.
const HOOK_EVENTS: &[(&str, &str)] =
    &[("PreToolUse", "working"), ("Stop", "waiting"), ("Notification", "needs_input")];

/// Substring marker identifying a hook command as roost's own, independent of
/// the (variable) binary path — so a build whose binary moved, or an older
/// hand-copied hook from before this build, is recognized and replaced
/// in-place rather than duplicated:
/// - `__status`: this build's command (the internal subcommand, see `cli.rs`).
/// - `ROOST_SOCK`: any earlier hand-copied `nc`/`socat` hook from
///   `extensions/claude-code-hooks.md`, which referenced it directly.
///
/// ponytail: substring match, not a real parser — fine here because every
/// matching command is roost-authored text (either generated by us or copied
/// verbatim from our own docs); upgrade to something stricter if a user ever
/// reports an unrelated hook that happens to contain one of these.
fn is_roost_hook(command: &str) -> bool {
    command.contains("__status") || command.contains("ROOST_SOCK")
}

/// Merge roost's status hooks into the settings file at `settings_path`,
/// pointing each hook's command at `exe`. Returns a short message on any
/// actual change (installed, updated, or refused-to-touch), None when
/// nothing changed. Takes an explicit path (rather than resolving `~/.claude`
/// itself) so it's independently testable against a tempdir.
///
/// Safety contract, in order:
/// - Missing file → treated as `{}` (first install).
/// - Malformed JSON, or valid JSON that isn't an object → refuse to touch it
///   and say so, rather than guessing or overwriting.
/// - A `.bak` of the pristine (pre-roost) file is written once, before the
///   first modification ever made to it.
/// - Every unrelated key, and every non-roost hook entry, round-trips
///   unchanged (`preserve_order` on serde_json keeps key order too).
/// - Written atomically (temp file + rename).
fn merge_claude_hooks(settings_path: &Path, exe: &str) -> Option<String> {
    let raw = match std::fs::read_to_string(settings_path) {
        Ok(s) => Some(s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(_) => return Some(cannot_merge_msg()),
    };
    let mut root: serde_json::Value = match &raw {
        None => serde_json::json!({}),
        Some(s) => match serde_json::from_str(s) {
            Ok(v) => v,
            Err(_) => return Some(cannot_merge_msg()),
        },
    };
    let Some(obj) = root.as_object_mut() else { return Some(cannot_merge_msg()) };

    let mut inserted = false;
    let mut updated = false;
    for (event, status) in HOOK_EVENTS {
        match upsert_hook(obj, event, &hook_command(exe, status)) {
            HookChange::Inserted => inserted = true,
            HookChange::Updated => updated = true,
            HookChange::Unchanged => {}
        }
    }
    if !inserted && !updated {
        return None;
    }

    // Snapshot the file exactly as the user left it, once, before roost ever
    // writes to it — best effort, never blocks the install.
    if let Some(raw) = &raw {
        let bak = settings_path.with_extension("json.bak");
        if !bak.exists() {
            let _ = std::fs::write(&bak, raw);
        }
    }

    let out = serde_json::to_string_pretty(&root).ok()?;
    write_atomic(settings_path, &out)?;
    Some(if inserted {
        "installed the roost Claude Code hooks (~/.claude/settings.json)".into()
    } else {
        "updated the roost Claude Code hooks to match this build".into()
    })
}

fn cannot_merge_msg() -> String {
    "~/.claude/settings.json couldn't be safely merged (not valid JSON) — leaving it untouched. \
     Fix it, or add the hooks by hand (see extensions/claude-code-hooks.md), and roost will \
     manage them from then on."
        .into()
}

enum HookChange {
    Inserted,
    Updated,
    Unchanged,
}

/// Insert or update roost's hook for `event` within `root["hooks"][event]`
/// (an array of `{"hooks": [{"type": "command", "command": ...}]}` groups —
/// Claude Code's hook-config shape). Finds roost's existing entry anywhere in
/// that array via `is_roost_hook` and replaces its command in place; appends
/// a new group only if none is found. Never touches any other entry, group,
/// or key.
fn upsert_hook(
    root: &mut serde_json::Map<String, serde_json::Value>,
    event: &str,
    command: &str,
) -> HookChange {
    let hooks = root.entry("hooks").or_insert_with(|| serde_json::json!({}));
    let Some(hooks) = hooks.as_object_mut() else { return HookChange::Unchanged };
    let arr = hooks.entry(event).or_insert_with(|| serde_json::json!([]));
    let Some(arr) = arr.as_array_mut() else { return HookChange::Unchanged };

    for group in arr.iter_mut() {
        let Some(entries) = group.get_mut("hooks").and_then(|h| h.as_array_mut()) else {
            continue;
        };
        for entry in entries.iter_mut() {
            let is_ours =
                entry.get("command").and_then(|c| c.as_str()).is_some_and(is_roost_hook);
            if !is_ours {
                continue;
            }
            if entry.get("command").and_then(|c| c.as_str()) == Some(command) {
                return HookChange::Unchanged;
            }
            if let Some(o) = entry.as_object_mut() {
                o.insert("command".into(), serde_json::json!(command));
            }
            return HookChange::Updated;
        }
    }
    arr.push(serde_json::json!({ "hooks": [{ "type": "command", "command": command }] }));
    HookChange::Inserted
}

/// The shell command a hook entry runs: roost's own binary, invoked with the
/// internal `__status` subcommand (see `cli.rs`) instead of piping through
/// `nc`/`socat` — no netcat dependency, identical on macOS and Linux.
/// Claude Code runs `command` through a shell, so the path is quoted.
fn hook_command(exe: &str, status: &str) -> String {
    format!("{} __status {status}", shell_quote(exe))
}

/// POSIX-safe single-quoting: wrap in `'...'`, escaping embedded `'` as
/// `'\''`. Handles spaces in the exe path (common on macOS, e.g. under `~/Library`).
fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// Write via a temp file + rename so a crash can't leave a half-written file
/// an agent or Claude Code would try to load.
fn write_atomic(target: &Path, contents: &str) -> Option<()> {
    let mut tmp = target.as_os_str().to_os_string();
    tmp.push(".tmp");
    let tmp = PathBuf::from(tmp);
    std::fs::write(&tmp, contents).ok()?;
    std::fs::rename(&tmp, target).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("roost-claude-hooks-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn hook_commands(root: &serde_json::Value, event: &str) -> Vec<String> {
        root["hooks"][event]
            .as_array()
            .into_iter()
            .flatten()
            .flat_map(|g| g["hooks"].as_array().into_iter().flatten())
            .map(|h| h["command"].as_str().unwrap().to_string())
            .collect()
    }

    #[test]
    fn installs_into_an_absent_file() {
        let dir = scratch_dir("absent");
        let path = dir.join("settings.json");
        let msg = merge_claude_hooks(&path, "/opt/roost/roost").expect("should install");
        assert!(msg.contains("installed"), "{msg}");
        let root: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        for (event, status) in HOOK_EVENTS {
            let cmds = hook_commands(&root, event);
            assert_eq!(cmds.len(), 1, "{event}: {cmds:?}");
            assert_eq!(cmds[0], format!("'/opt/roost/roost' __status {status}"));
        }
        assert!(!path.with_extension("json.tmp").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn installs_into_an_empty_object() {
        let dir = scratch_dir("empty");
        let path = dir.join("settings.json");
        std::fs::write(&path, "{}").unwrap();
        let msg = merge_claude_hooks(&path, "/opt/roost/roost").expect("should install");
        assert!(msg.contains("installed"), "{msg}");
        let root: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(hook_commands(&root, "Stop").len(), 1);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn unrelated_settings_and_key_order_survive() {
        let dir = scratch_dir("unrelated");
        let path = dir.join("settings.json");
        // zzz_last before aaa_first on purpose: proves order is preserved
        // (not alphabetized) through the round-trip.
        std::fs::write(
            &path,
            r#"{"zzz_last": 1, "model": "sonnet", "permissions": {"allow": ["Bash(ls:*)"]}, "aaa_first": 2, "hooks": {"PostToolUse": [{"hooks": [{"type": "command", "command": "echo unrelated"}]}]}}"#,
        )
        .unwrap();
        merge_claude_hooks(&path, "/opt/roost/roost").expect("should install");
        let out = std::fs::read_to_string(&path).unwrap();
        let root: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(root["model"], "sonnet");
        assert_eq!(root["permissions"]["allow"][0], "Bash(ls:*)");
        assert_eq!(root["hooks"]["PostToolUse"][0]["hooks"][0]["command"], "echo unrelated");
        assert!(
            out.find("zzz_last").unwrap() < out.find("aaa_first").unwrap(),
            "keys were reordered:\n{out}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn the_users_own_hooks_in_the_same_events_survive() {
        let dir = scratch_dir("user-hooks");
        let path = dir.join("settings.json");
        std::fs::write(
            &path,
            r#"{"hooks": {"PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "command": "echo mine"}]}]}}"#,
        )
        .unwrap();
        merge_claude_hooks(&path, "/opt/roost/roost").expect("should install");
        let root: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let groups = root["hooks"]["PreToolUse"].as_array().unwrap();
        assert_eq!(groups.len(), 2, "user's group must survive alongside roost's own: {groups:?}");
        assert_eq!(groups[0]["hooks"][0]["command"], "echo mine");
        assert_eq!(groups[0]["matcher"], "Bash");
        assert_eq!(groups[1]["hooks"][0]["command"], "'/opt/roost/roost' __status working");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn running_twice_does_not_duplicate() {
        let dir = scratch_dir("idempotent");
        let path = dir.join("settings.json");
        merge_claude_hooks(&path, "/opt/roost/roost").expect("first run installs");
        let second = merge_claude_hooks(&path, "/opt/roost/roost");
        assert!(second.is_none(), "unchanged second run must be silent: {second:?}");
        let root: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        for (event, _) in HOOK_EVENTS {
            assert_eq!(hook_commands(&root, event).len(), 1, "{event} duplicated");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_stale_roost_entry_is_replaced_not_appended() {
        let dir = scratch_dir("stale");
        let path = dir.join("settings.json");
        merge_claude_hooks(&path, "/old/path/roost").expect("first run installs");
        let msg = merge_claude_hooks(&path, "/new/path/roost").expect("moved binary must update");
        assert!(msg.contains("updated"), "{msg}");
        let root: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        for (event, status) in HOOK_EVENTS {
            let cmds = hook_commands(&root, event);
            assert_eq!(cmds, vec![format!("'/new/path/roost' __status {status}")], "{event}");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_hand_copied_legacy_nc_hook_is_recognized_and_replaced() {
        // The pre-this-change docs told users to hand-copy an `nc`-piping
        // command referencing $ROOST_SOCK directly, for all three events.
        // That's exactly the "rot" this feature exists to fix — every one
        // must be upgraded in place, not left running (broken, on macOS)
        // alongside a second, working entry.
        let dir = scratch_dir("legacy-nc");
        let path = dir.join("settings.json");
        let legacy_group = |status: &str| {
            let command = format!(
                "[ -n \"$ROOST_PANE\" ] && printf '{{\"status\":\"{status}\"}}' | nc -U -q0 \"$ROOST_SOCK\" 2>/dev/null; true"
            );
            serde_json::json!({ "hooks": [{ "type": "command", "command": command }] })
        };
        let seed = serde_json::json!({ "hooks": {
            "PreToolUse": [legacy_group("working")],
            "Stop": [legacy_group("waiting")],
            "Notification": [legacy_group("needs_input")],
        }});
        std::fs::write(&path, seed.to_string()).unwrap();

        let msg = merge_claude_hooks(&path, "/opt/roost/roost").expect("legacy hooks must be updated");
        assert!(msg.contains("updated"), "{msg}");
        let root: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        for (event, status) in HOOK_EVENTS {
            let cmds = hook_commands(&root, event);
            assert_eq!(cmds, vec![format!("'/opt/roost/roost' __status {status}")], "{event}: {cmds:?}");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn malformed_json_is_refused_not_overwritten() {
        let dir = scratch_dir("malformed");
        let path = dir.join("settings.json");
        let original = "{ this is not valid json";
        std::fs::write(&path, original).unwrap();
        let msg = merge_claude_hooks(&path, "/opt/roost/roost").expect("must explain the refusal");
        assert!(msg.to_lowercase().contains("json"), "{msg}");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), original, "malformed file must be left untouched");
        assert!(!path.with_extension("json.bak").exists());
        assert!(!path.with_extension("json.tmp").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn backs_up_the_pristine_file_once_before_the_first_write() {
        let dir = scratch_dir("backup");
        let path = dir.join("settings.json");
        let original = r#"{"model": "sonnet"}"#;
        std::fs::write(&path, original).unwrap();
        merge_claude_hooks(&path, "/old/roost").expect("install");
        let bak = path.with_extension("json.bak");
        assert_eq!(std::fs::read_to_string(&bak).unwrap(), original);

        // A later change (stale entry) must not clobber that first snapshot
        // with an already-roost-modified version.
        merge_claude_hooks(&path, "/new/roost").expect("update");
        assert_eq!(std::fs::read_to_string(&bak).unwrap(), original);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
