name: Release request
on:
  push:
    branches: [main]
    paths: ['.github/release-request']
permissions:
  contents: write
concurrency:
  group: release
  cancel-in-progress: false
jobs:
  release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
